#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

cd MC_A_0_b_0

for ((x = 0; x < 122; x = x + 1))

do

if ((x == 9))
then
continue
fi
if ((x == 59))
then
continue
fi
if ((x == 91))
then
continue
fi
if ((x == 93))
then
continue
fi
if ((x == 101))
then
continue
fi
if ((x == 107))
then
continue
fi
if ((x == 121))
then
continue
fi


mv MC_A_0_b_0_Octet_"$x"_ssHist.root MC_A_0_b_0_Octet_"$x"_ssHist_allTypes.root



done

echo "Done running bash script"
