#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

cd /mnt/Data/xuansun/analyzed_files/2012-2013_geom_twiddledAndBaselineSimulations/A_0_b_0/

for ((x = 0; x < 100; x = x + 1))

do


mv BLIND_SimAnalyzed_2011-2012_Beta_paramSet_100_"$x"_type0.root BLIND_SimAnalyzed_2012-2013_Beta_paramSet_100_"$x"_type0.root



done

echo "Done running bash script"
