#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

cd ../Asymmetry_Data_Fitting/FitWindowStudy_April2019/

for ((wLow = 165; wLow <= 405; wLow = wLow + 10))

do

for ((wHigh = 645; wHigh <= 645; wHigh = wHigh + 1))

do

make
./blinded_postMBProcessed_asymm_fitWindow $wLow $wHigh
make clean


done

done

echo "Done running bash script"
