#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

cd ../SuperSum_Data_EnergyWindow/

make

for ((wLow = 17; wLow <= 41; wLow = wLow + 1))

do

for ((wHigh = 65; wHigh <= 65; wHigh = wHigh + 1))

do

for ((x = 0; x < 60; x = x + 1))

do

if ((x == 9))
then
continue
fi
if ((x == 59))
then
continue
fi


./newXuanFitter_binWindowVariation $x $wLow $wHigh



done

done

done

make clean

echo "Done running bash script"
