#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

cd ../End_Point_Studies/

for ((x = 0; x < 100; x = x + 1))

do

make
./kurie $x
make clean

done

echo "Done running bash script"
