#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

cd ../Twiddle_End_Point_Studies/

make

for ((x = 1; x < 7750; x = x + 1))

do

./newXuanFitter $x

done

make clean

echo "Done running bash script"
