#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

# in this loop, set the number of .mac files you want to generate
# this loop variable also counts the Evts_#.root trees you read in. Only used for betas

cd ../PositionCuts/

for ((x = 80; x < 122; x = x + 1))

do

if ((x == 60))
then
continue
fi
if ((x == 67))
then
continue
fi
if ((x == 69))
then
continue
fi
if ((x == 91))
then
continue
fi
if ((x == 93))
then
continue
fi
if ((x == 101))
then
continue
fi
if ((x == 107))
then
continue
fi
if ((x == 121))
then
continue
fi

make
./ssDataHist_radialCuts $x
make clean

done

echo "Done running bash script"
